/*
 * IONOS DBaaS MariaDB REST API
 * An enterprise-grade Database is provided as a Service (DBaaS) solution that can be managed through a browser-based \"Data Center Designer\" (DCD) tool or via an easy to use API.  The API allows you to create additional MariaDB database clusters or modify existing ones. It is designed to allow users to leverage the same power and flexibility found within the DCD visual tool. Both tools are consistent with their concepts and lend well to making the experience smooth and intuitive. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ionoscloud.dbaasmariadb.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.ionoscloud.dbaasmariadb.model.BaseBackup;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;

/**
 * A backup object.
 */
@ApiModel(description = "A backup object.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-23T08:43:50.943261Z[Etc/UTC]")

public class Backup {
  
  public static final String SERIALIZED_NAME_CLUSTER_ID = "clusterId";
  @SerializedName(SERIALIZED_NAME_CLUSTER_ID)
  private String clusterId;


  public static final String SERIALIZED_NAME_LOCATION = "location";
  @SerializedName(SERIALIZED_NAME_LOCATION)
  private String location;


  public static final String SERIALIZED_NAME_EARLIEST_RECOVERY_TARGET_TIME = "earliestRecoveryTargetTime";
  @SerializedName(SERIALIZED_NAME_EARLIEST_RECOVERY_TARGET_TIME)
  private OffsetDateTime earliestRecoveryTargetTime;


  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Integer size;


  public static final String SERIALIZED_NAME_BASE_BACKUPS = "baseBackups";
  @SerializedName(SERIALIZED_NAME_BASE_BACKUPS)
  private List<BaseBackup> baseBackups = null;

  

  public Backup clusterId(String clusterId) {
    
    this.clusterId = clusterId;
    return this;
  }

   /**
   * The unique ID of the cluster that was backed up.
   * @return clusterId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "498ae72f-411f-11eb-9d07-046c59cc737e", value = "The unique ID of the cluster that was backed up.")

  public String getClusterId() {
    return clusterId;
  }


  public void setClusterId(String clusterId) {
    this.clusterId = clusterId;
  }



  public Backup location(String location) {
    
    this.location = location;
    return this;
  }

   /**
   * The S3 location where the backups will be stored.
   * @return location
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "de", value = "The S3 location where the backups will be stored.")

  public String getLocation() {
    return location;
  }


  public void setLocation(String location) {
    this.location = location;
  }



  public Backup earliestRecoveryTargetTime(OffsetDateTime earliestRecoveryTargetTime) {
    
    this.earliestRecoveryTargetTime = earliestRecoveryTargetTime;
    return this;
  }

   /**
   * The oldest available timestamp to which you can restore.
   * @return earliestRecoveryTargetTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2021-10-23T01:21:10Z", value = "The oldest available timestamp to which you can restore.")

  public OffsetDateTime getEarliestRecoveryTargetTime() {
    return earliestRecoveryTargetTime;
  }


  public void setEarliestRecoveryTargetTime(OffsetDateTime earliestRecoveryTargetTime) {
    this.earliestRecoveryTargetTime = earliestRecoveryTargetTime;
  }



  public Backup size(Integer size) {
    
    this.size = size;
    return this;
  }

   /**
   * Size of all base backups in MiB. This is at least the sum of all base backup sizes. 
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2052", value = "Size of all base backups in MiB. This is at least the sum of all base backup sizes. ")

  public Integer getSize() {
    return size;
  }


  public void setSize(Integer size) {
    this.size = size;
  }



  public Backup baseBackups(List<BaseBackup> baseBackups) {
    
    this.baseBackups = baseBackups;
    return this;
  }

  public Backup addBaseBackupsItem(BaseBackup baseBackupsItem) {
    if (this.baseBackups == null) {
      this.baseBackups = new ArrayList<BaseBackup>();
    }
    this.baseBackups.add(baseBackupsItem);
    return this;
  }

   /**
   * Get baseBackups
   * @return baseBackups
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BaseBackup> getBaseBackups() {
    return baseBackups;
  }


  public void setBaseBackups(List<BaseBackup> baseBackups) {
    this.baseBackups = baseBackups;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Backup backup = (Backup) o;
    return Objects.equals(this.clusterId, backup.clusterId) && Objects.equals(this.location, backup.location) && Objects.equals(this.earliestRecoveryTargetTime, backup.earliestRecoveryTargetTime) && Objects.equals(this.size, backup.size) && Objects.equals(this.baseBackups, backup.baseBackups);
  }




  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Backup {\n");
    
    sb.append("    clusterId: ").append(toIndentedString(clusterId)).append("\n");

    sb.append("    location: ").append(toIndentedString(location)).append("\n");

    sb.append("    earliestRecoveryTargetTime: ").append(toIndentedString(earliestRecoveryTargetTime)).append("\n");

    sb.append("    size: ").append(toIndentedString(size)).append("\n");

    sb.append("    baseBackups: ").append(toIndentedString(baseBackups)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

